package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// emitAliases writes <resource>_aliases.go — convenience re-exports so
// consumers can reach every storage-layer identifier for a resource
// through a single import.
//
// Hand-written (not protogen) because the file needs a blank import
// of "embed" for the go:embed directive, and protogen's import
// tracking doesn't emit blank imports.
func emitAliases(p *ResourcePlan) error {
	source := renderAliases(p, string(p.Message.Desc.FullName()))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("gofmt aliases for %s: %w", p.SymbolPrefix, err)
	}
	abs := filepath.Join(p.RepoRoot, p.GoDir, p.FilenamePrefix+"_aliases.go")
	if err := os.MkdirAll(filepath.Dir(abs), 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(abs), err)
	}
	if err := os.WriteFile(abs, formatted, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", abs, err)
	}
	return nil
}

// renderAliases is the pure source-building half of emitAliases,
// parameterised on the proto FQN so unit tests don't need to build a
// real protogen.Message to exercise the template.
func renderAliases(p *ResourcePlan, protoFQN string) string {
	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-go-jet. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n\n", p.ProtoFile)
	fmt.Fprintf(&b, "package %s\n\n", p.GoPackageName)
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t_ \"embed\" // needed for the go:embed directive on %sDDL below.\n", p.SymbolPrefix)
	b.WriteString("\n")
	b.WriteString("\t\"github.com/go-jet/jet/v2/postgres\"\n")
	b.WriteString("\n")
	b.WriteString("\taipjet \"github.com/redpanda-data/protoc-gen-go-jet/pkg/aip/jet\"\n")
	fmt.Fprintf(&b, "\tmodel %q\n", p.JetModelImport)
	fmt.Fprintf(&b, "\ttable %q\n", p.JetTableImport)
	if hasColumn(p, "updated_by") {
		b.WriteString("\n")
		fmt.Fprintf(&b, "\tproto %q\n", string(p.ProtoGoIdent.GoImportPath))
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// %sResourceType is the fully-qualified proto name of this resource.\n", p.SymbolPrefix)
	b.WriteString("// Use it for authorization strings, structured logs, and anywhere\n")
	b.WriteString("// you'd otherwise hand-write the proto FQN.\n")
	fmt.Fprintf(&b, "const %sResourceType = %q\n\n", p.SymbolPrefix, protoFQN)

	fmt.Fprintf(&b, "// %sModel is the go-jet-generated row struct for this resource's table.\n", p.SymbolPrefix)
	b.WriteString("// Re-exported so callers have one import surface for storage types.\n")
	fmt.Fprintf(&b, "type %sModel = model.%s\n\n", p.SymbolPrefix, p.JetStructName)

	fmt.Fprintf(&b, "// %sTable is the go-jet-generated query-builder table for this resource.\n", p.SymbolPrefix)
	fmt.Fprintf(&b, "// Use %sTable.<ColumnName> directly in SQL builder expressions.\n", p.SymbolPrefix)
	fmt.Fprintf(&b, "var %sTable = table.%s\n\n", p.SymbolPrefix, p.JetStructName)

	fmt.Fprintf(&b, "// %sUpdateAll returns an UPDATE statement with every mutable column\n", p.SymbolPrefix)
	b.WriteString("// pre-selected — every persisted field except primary-key members,\n")
	b.WriteString("// synthesized storage columns (tenant_id / user_id), and fields marked\n")
	b.WriteString("// `immutable: true` in (storage.v1.column). updated_at participates\n")
	b.WriteString("// automatically (the repo sets it on every mutation).\n")
	b.WriteString("//\n")
	b.WriteString("// Chain .MODEL(row).WHERE(...).RETURNING(...) to finish. A new persisted\n")
	b.WriteString("// proto field is picked up automatically on regen — no hand-edit of the\n")
	b.WriteString("// repository's column list, no silent update-drops.\n")
	b.WriteString("//\n")
	b.WriteString("// Returned as a function rather than a slice because go-jet's UPDATE\n")
	b.WriteString("// takes `...jet.Column` (an internal-package variadic), and Go does not\n")
	b.WriteString("// allow spreading an []postgres.Column into it. The function inlines\n")
	b.WriteString("// the spread where the type is known.\n")
	fmt.Fprintf(&b, "func %sUpdateAll() postgres.UpdateStatement {\n", p.SymbolPrefix)
	fmt.Fprintf(&b, "\treturn %sTable.UPDATE(\n", p.SymbolPrefix)
	for _, col := range mutableJetFields(p) {
		fmt.Fprintf(&b, "\t\t%sTable.%s,\n", p.SymbolPrefix, col)
	}
	b.WriteString("\t)\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// %sFilterFields returns the AIP-160 filter field binding for this\n", p.SymbolPrefix)
	b.WriteString("// resource — every column the translator can produce a WHERE clause\n")
	b.WriteString("// for, mapped to its jet column. Pass it directly to\n")
	b.WriteString("// aipjet.FilterToCondition:\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "//\tcond, err := aipjet.FilterToCondition(params.Filter, gen.%sFilterFields())\n", p.SymbolPrefix)
	b.WriteString("//\n")
	b.WriteString("// Columns with kinds the filter grammar can't bind (JSONB, BYTEA)\n")
	b.WriteString("// are excluded — the translator rejects them anyway, and exposing\n")
	b.WriteString("// them as filterable would let callers write filters that can only\n")
	b.WriteString("// fail. Durations participate as BIGINT nanoseconds and accept\n")
	b.WriteString("// bare-int literals or duration(\"5m\"). Repeated-text columns\n")
	b.WriteString("// (TEXT[]) participate via containment — `col = \"x\"` compiles to\n")
	b.WriteString("// `'x' = ANY(col)` (see stringArrayOp).\n")
	fmt.Fprintf(&b, "func %sFilterFields() aipjet.FilterFields {\n", p.SymbolPrefix)
	b.WriteString("\treturn aipjet.FilterFields{\n")
	for _, f := range filterableJetFields(p) {
		fmt.Fprintf(&b, "\t\t%q: %sTable.%s,\n", f.Key, p.SymbolPrefix, f.JetField)
	}
	// JSONB indexed paths are exposed to the filter grammar via
	// `postgres.RawString("col->>'path'")` — the raw accessor is a
	// StringExpression, which the filter translator dispatches to
	// stringOp like any text column. Only indexed paths land here so
	// the filter grammar can't coax users into seqscans on arbitrary
	// JSONB sub-fields.
	for _, f := range jsonbFilterPaths(p) {
		fmt.Fprintf(&b, "\t\t%q: postgres.RawString(%q),\n", f.Key, f.Expr)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// %sDDL is the canonical SQL schema for this resource, embedded at\n", p.SymbolPrefix)
	fmt.Fprintf(&b, "// build time. Apply it to a database with db.Exec(ctx, %sDDL).\n", p.SymbolPrefix)
	b.WriteString("//\n")
	b.WriteString("// Useful for tests and fixtures that want the schema without reaching\n")
	b.WriteString("// for the migrations directory — the bytes here are the exact ddl.sql\n")
	b.WriteString("// the plugin emits and the drift check asserts against migrations.\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "//go:embed %s_ddl.sql\n", p.FilenamePrefix)
	fmt.Fprintf(&b, "var %sDDL string\n", p.SymbolPrefix)

	hasCreatedBy := hasColumn(p, "created_by")
	hasUpdatedBy := hasColumn(p, "updated_by")
	protoType := "proto." + p.ProtoGoIdent.GoName

	// StampCreate sets both audit columns, so it needs the pair present.
	if hasCreatedBy && hasUpdatedBy {
		fmt.Fprintf(&b, "\n// %sStampCreate sets created_by and updated_by before a Create call.\n", p.SymbolPrefix)
		fmt.Fprint(&b, "// Call this in the service layer with the caller's identity (e.g. email) before repo.Create.\n")
		fmt.Fprintf(&b, "func %sStampCreate(r *%s, callerEmail string) {\n", p.SymbolPrefix, protoType)
		fmt.Fprint(&b, "\tr.CreatedBy = callerEmail\n\tr.UpdatedBy = callerEmail\n}\n\n")
	}
	if hasUpdatedBy {
		fmt.Fprintf(&b, "// %sStampUpdate sets updated_by before an Update call.\n", p.SymbolPrefix)
		fmt.Fprint(&b, "// Call this in the service layer with the caller's identity (e.g. email) before repo.Update.\n")
		fmt.Fprintf(&b, "func %sStampUpdate(r *%s, callerEmail string) {\n", p.SymbolPrefix, protoType)
		fmt.Fprint(&b, "\tr.UpdatedBy = callerEmail\n}\n")
	}

	return b.String()
}

// hasColumn reports whether the plan includes a column with the given DB name.
func hasColumn(p *ResourcePlan, dbName string) bool {
	for _, c := range p.Columns {
		if c.DBName == dbName {
			return true
		}
	}
	return false
}

// filterableField pairs an AIP-160 filter identifier (the name a
// caller writes in the filter string) with the jet column field
// that backs it.
type filterableField struct {
	Key      string // DB column name — the identifier clients use in the filter string
	JetField string // jet table field name (CamelCase equivalent)
}

// filterableJetFields returns the columns the filter translator can
// bind to an AIP-160 comparison. Kinds the grammar can't express
// (JSONB anything, BYTEA, repeated-bytes, repeated-primitive-numeric,
// Synthesized) are excluded — exposing them as filterable would let a
// caller write a filter the translator always rejects.
//
// Durations are included: they're stored as BIGINT nanoseconds and
// bind through integerOp, which accepts bare int literals or
// duration("5m"). So `ttl > duration("5m")` compiles end-to-end.
//
// Repeated text kinds (repeated string → TEXT[], repeated enum →
// TEXT[] of names) are included and route through stringArrayOp,
// which handles AIP-160 "has" semantics on a list via PG's `= ANY()`
// operator. Only =, !=, : are valid on a TEXT[] column — ordering
// operators are rejected at the comparator, and NULL predicates work
// against the whole column like any other type.
//
// Tenant and user scoping columns stay excluded too: they're synthesized
// by the runtime, not caller-controlled, and letting the filter
// reference them would be a cross-tenant foot-gun (it'd bypass the
// service's implicit tenant scoping by asking for a specific tenant_id).
func filterableJetFields(p *ResourcePlan) []filterableField {
	var out []filterableField
	for _, c := range p.Columns {
		if c.Synthesized {
			continue
		}
		switch c.Kind {
		case KindScalar:
			// Nullable scalars render as pointers in the model
			// (*string, *int64, …) but the jet table column is the
			// same ColumnString/ColumnBool/… and binds to an AIP-160
			// comparison identically — a NULL row simply doesn't match
			// an equality predicate. Strip the pointer so nullable
			// scalars stay filterable.
			switch strings.TrimPrefix(c.JetGoType, "*") {
			case "string", "bool", "int32", "int64", "float32", "float64":
				out = append(out, filterableField{Key: c.DBName, JetField: c.JetFieldName})
			}
		case KindTimestamp, KindEnumAsText, KindDuration,
			KindRepeatedText, KindRepeatedEnum:
			out = append(out, filterableField{Key: c.DBName, JetField: c.JetFieldName})
		}
	}
	return out
}

// jsonbFilterPath pairs an AIP-160 filter identifier (dotted form) with
// the raw JSONB accessor expression the translator should emit. Each
// entry is generated from a column's jsonb_indexed_paths option.
type jsonbFilterPath struct {
	Key  string // "column_name.path" — the identifier clients use in the filter
	Expr string // "column_name->>'path'" — SQL accessor for StringExpression
}

// jsonbFilterPaths returns the full list of dotted-path filter
// identifiers the plugin auto-registers on this resource's
// FilterFields. Ordered: column declaration order, paths in the order
// the caller listed them. Deterministic output keeps the emitted
// aliases file byte-stable across runs.
func jsonbFilterPaths(p *ResourcePlan) []jsonbFilterPath {
	var out []jsonbFilterPath
	for _, c := range p.Columns {
		for _, path := range c.JSONBIndexedPaths {
			out = append(out, jsonbFilterPath{
				Key:  c.DBName + "." + path,
				Expr: jsonbPathExpr(c.DBName, path),
			})
		}
	}
	// Oneof JSON columns are named after the oneof's base name
	// (<base> for the JSONB value, <base>_kind for the discriminator).
	// Indexed paths register as `<base>.<path>` — same shape as the
	// scalar column case, so AIP-160 dotted paths like `cloud.aws` work.
	for _, oc := range p.OneofColumns {
		for _, path := range oc.JSONBIndexedPaths {
			out = append(out, jsonbFilterPath{
				Key:  oc.JSONColumn + "." + path,
				Expr: jsonbPathExpr(oc.JSONColumn, path),
			})
		}
	}
	return out
}

// mutableJetFields returns the jet-model field names in declaration
// order that should participate in an UPDATE. Synthesized storage
// columns (tenant_id / user_id), primary-key members, fields
// annotated `immutable: true`, and generated columns (PG computes
// them; UPDATE SET on a GENERATED ALWAYS column is a SQL error) are
// excluded. Oneof pair columns (<name>_kind + <name>) are included —
// the discriminator and the JSON payload both need to re-write when
// the variant changes.
func mutableJetFields(p *ResourcePlan) []string {
	pk := make(map[string]bool, len(p.PrimaryKey))
	for _, k := range p.PrimaryKey {
		pk[k] = true
	}
	var out []string
	for _, c := range p.Columns {
		if c.Synthesized || c.Immutable || pk[c.DBName] || c.GeneratedExpr != "" {
			continue
		}
		out = append(out, c.JetFieldName)
	}
	for _, oc := range p.OneofColumns {
		out = append(out, oc.JetKindField, oc.JetJSONField)
	}
	return out
}
