package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// emitRpsqlRead writes <resource>_rpsql.go — a type-safe Redpanda SQL read
// model bound to the message's external catalog table. Hand-written (like
// emit_aliases.go) for precise import control.
func emitRpsqlRead(p *rpsqlReadPlan) error {
	source := renderRpsqlRead(p, string(p.Message.Desc.FullName()))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("gofmt rpsql read model for %s: %w\n%s", p.SymbolPrefix, err, source)
	}
	abs := filepath.Join(p.RepoRoot, p.GoDir, p.FilenamePrefix+"_rpsql.go")
	if err := os.MkdirAll(filepath.Dir(abs), 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(abs), err)
	}
	if err := os.WriteFile(abs, formatted, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", abs, err)
	}
	return nil
}

func renderRpsqlRead(p *rpsqlReadPlan, protoFQN string) string {
	prefix := p.SymbolPrefix
	typeName := prefix + "Read"
	rowType := lowerFirst(prefix) + "ScanRow"

	// Which optional imports the Select path needs.
	var needTime, needTimestamppb, needDurationpb bool
	for _, c := range p.ScanCols {
		if c.Type == "*time.Time" {
			needTime = true
		}
	}
	forEachLeaf(p.AsmRoot, func(n rpsqlAsmNode) {
		switch n.Conv {
		case "timestamp":
			needTimestamppb = true
		case "duration":
			needDurationpb, needTime = true, true
		}
	})

	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-go-jet. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n\n", p.ProtoFile)
	fmt.Fprintf(&b, "package %s\n\n", p.GoPackageName)

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	if needTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/go-jet/jet/v2/postgres\"\n")
	b.WriteString("\t\"github.com/go-jet/jet/v2/qrm\"\n")
	if needTimestamppb {
		b.WriteString("\t\"google.golang.org/protobuf/types/known/timestamppb\"\n")
	}
	if needDurationpb {
		b.WriteString("\t\"google.golang.org/protobuf/types/known/durationpb\"\n")
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "\tpb %q\n", p.ProtoImportPath)
	b.WriteString("\t\"github.com/redpanda-data/protoc-gen-go-jet/pkg/rpsql\"\n")
	b.WriteString(")\n\n")

	// Type + constructor + CTE.
	fmt.Fprintf(&b, "// %s is a type-safe Redpanda SQL read model for %s,\n", typeName, protoFQN)
	fmt.Fprintf(&b, "// read from the external catalog table %s => %s.\n", p.Catalog, p.Table)
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Select returns fully-formed *pb.%s values. For custom analytics use the\n", p.ProtoGoType)
	b.WriteString("// column accessors directly with postgres.WITH(...).\n")
	fmt.Fprintf(&b, "type %s struct {\n\tct rpsql.CatalogTable\n}\n\n", typeName)

	fmt.Fprintf(&b, "// New%s builds the read model over %s => %s.\n", typeName, p.Catalog, p.Table)
	fmt.Fprintf(&b, "func New%s() %s {\n", typeName, typeName)
	fmt.Fprintf(&b, "\treturn %s{ct: rpsql.NewCatalogTable(%q, %q, %q)}\n}\n\n", typeName, p.CTEName, p.Catalog, p.Table)

	fmt.Fprintf(&b, "// CTE returns the catalog CTE; pass it to postgres.WITH(...) and use it as\n")
	b.WriteString("// the FROM target of the outer query.\n")
	fmt.Fprintf(&b, "func (t %s) CTE() postgres.CommonTableExpression { return t.ct.CTE() }\n\n", typeName)

	// Column accessors.
	for _, a := range p.Accessors {
		if a.SQL != "" {
			fmt.Fprintf(&b, "// %s reads %s.\n", a.Method, a.SQL)
		}
		fmt.Fprintf(&b, "func (t %s) %s() %s { return %s }\n\n", typeName, a.Method, a.Return, a.Body)
	}

	// Unexported scan row.
	fmt.Fprintf(&b, "type %s struct {\n", rowType)
	for _, c := range p.ScanCols {
		fmt.Fprintf(&b, "\t%s %s `alias:%q`\n", c.Field, c.Type, c.Alias)
	}
	b.WriteString("}\n\n")

	// Select.
	fmt.Fprintf(&b, "// Select reads %s => %s and returns the rows as *pb.%s.\n", p.Catalog, p.Table, p.ProtoGoType)
	b.WriteString("// Optional predicates are ANDed into the WHERE clause. Repeated / array\n")
	b.WriteString("// fields are left zero-valued (rpsql cannot read them yet).\n")
	fmt.Fprintf(&b, "func (t %s) Select(ctx context.Context, db qrm.Queryable, where ...postgres.BoolExpression) ([]*pb.%s, error) {\n", typeName, p.ProtoGoType)
	b.WriteString("\tq := postgres.SELECT(\n")
	for _, c := range p.ScanCols {
		fmt.Fprintf(&b, "\t\t%s.AS(%q),\n", c.Expr, c.Alias)
	}
	b.WriteString("\t).FROM(t.CTE())\n")
	b.WriteString("\tif len(where) > 0 {\n")
	b.WriteString("\t\tcond := where[0]\n")
	b.WriteString("\t\tfor _, w := range where[1:] {\n\t\t\tcond = cond.AND(w)\n\t\t}\n")
	b.WriteString("\t\tq = q.WHERE(cond)\n\t}\n")
	fmt.Fprintf(&b, "\tvar rows []%s\n", rowType)
	b.WriteString("\tif err := postgres.WITH(t.CTE())(q).QueryContext(ctx, db, &rows); err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(&b, "\tout := make([]*pb.%s, 0, len(rows))\n", p.ProtoGoType)
	b.WriteString("\tfor i := range rows {\n\t\tr := &rows[i]\n")
	fmt.Fprintf(&b, "\t\tm := &pb.%s{}\n", p.ProtoGoType)
	ctr := 0
	for _, n := range p.AsmRoot {
		emitAsm(&b, n, "m", "\t\t", &ctr)
	}
	b.WriteString("\t\tout = append(out, m)\n\t}\n")
	b.WriteString("\treturn out, nil\n}\n\n")

	if len(p.SkippedRepeated) > 0 {
		b.WriteString("// Omitted fields (repeated / map): rpsql cannot yet read array or\n")
		b.WriteString("// composite-array columns, so these have no accessor and Select leaves\n")
		b.WriteString("// them zero-valued:\n")
		for _, s := range p.SkippedRepeated {
			fmt.Fprintf(&b, "//   - %s\n", s)
		}
	}

	return b.String()
}

// emitAsm writes the proto-assembly for one node into target (a *pb.X var).
func emitAsm(b *strings.Builder, n rpsqlAsmNode, target, indent string, ctr *int) {
	if n.Message {
		*ctr++
		sub := fmt.Sprintf("sub%d", *ctr)
		guard := strings.Join(leafGuards(n, "r"), " || ")
		fmt.Fprintf(b, "%sif %s {\n", indent, guard)
		fmt.Fprintf(b, "%s\t%s := &pb.%s{}\n", indent, sub, n.MsgGoType)
		for _, c := range n.Children {
			emitAsm(b, c, sub, indent+"\t", ctr)
		}
		fmt.Fprintf(b, "%s\t%s.%s = %s\n", indent, target, n.ProtoField, sub)
		fmt.Fprintf(b, "%s}\n", indent)
		return
	}
	sf := "r." + n.ScanField
	switch n.Conv {
	case "scalarPtr":
		fmt.Fprintf(b, "%s%s.%s = %s\n", indent, target, n.ProtoField, sf)
	case "scalarValue":
		fmt.Fprintf(b, "%sif %s != nil {\n%s\t%s.%s = *%s\n%s}\n", indent, sf, indent, target, n.ProtoField, sf, indent)
	case "enumValue":
		fmt.Fprintf(b, "%sif %s != nil {\n%s\t%s.%s = pb.%s(pb.%s_value[*%s])\n%s}\n",
			indent, sf, indent, target, n.ProtoField, n.EnumGoType, n.EnumGoType, sf, indent)
	case "enumPtr":
		fmt.Fprintf(b, "%sif %s != nil {\n%s\te := pb.%s(pb.%s_value[*%s])\n%s\t%s.%s = &e\n%s}\n",
			indent, sf, indent, n.EnumGoType, n.EnumGoType, sf, indent, target, n.ProtoField, indent)
	case "timestamp":
		fmt.Fprintf(b, "%sif %s != nil {\n%s\t%s.%s = timestamppb.New(*%s)\n%s}\n", indent, sf, indent, target, n.ProtoField, sf, indent)
	case "duration":
		fmt.Fprintf(b, "%sif %s != nil {\n%s\t%s.%s = durationpb.New(time.Duration(*%s))\n%s}\n", indent, sf, indent, target, n.ProtoField, sf, indent)
	}
}

// leafGuards returns `<prefix>.<scanField> != nil` for every leaf under n, so a
// composite is only instantiated when at least one member is present.
func leafGuards(n rpsqlAsmNode, prefix string) []string {
	var out []string
	forEachLeaf(n.Children, func(l rpsqlAsmNode) {
		out = append(out, fmt.Sprintf("%s.%s != nil", prefix, l.ScanField))
	})
	if len(out) == 0 {
		out = []string{"true"}
	}
	return out
}

func forEachLeaf(nodes []rpsqlAsmNode, fn func(rpsqlAsmNode)) {
	for _, n := range nodes {
		if n.Message {
			forEachLeaf(n.Children, fn)
		} else {
			fn(n)
		}
	}
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
