package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// emitRpsqlRead writes <resource>_rpsql.go — a type-safe Redpanda SQL read
// model bound to the message's external catalog table. Hand-written (like
// emit_aliases.go) for precise import control.
func emitRpsqlRead(p *rpsqlReadPlan) error {
	source := renderRpsqlRead(p, string(p.Message.Desc.FullName()))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("gofmt rpsql read model for %s: %w", p.SymbolPrefix, err)
	}
	abs := filepath.Join(p.RepoRoot, p.GoDir, p.FilenamePrefix+"_rpsql.go")
	if err := os.MkdirAll(filepath.Dir(abs), 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(abs), err)
	}
	if err := os.WriteFile(abs, formatted, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", abs, err)
	}
	return nil
}

// renderRpsqlRead is the pure source-building half of emitRpsqlRead,
// parameterised on the proto FQN so tests don't need a real protogen.Message.
func renderRpsqlRead(p *rpsqlReadPlan, protoFQN string) string {
	prefix := p.SymbolPrefix
	typeName := prefix + "Read"

	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-go-jet. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n\n", p.ProtoFile)
	fmt.Fprintf(&b, "package %s\n\n", p.GoPackageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/go-jet/jet/v2/postgres\"\n\n")
	b.WriteString("\t\"github.com/redpanda-data/protoc-gen-go-jet/pkg/rpsql\"\n")
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// %s is a type-safe Redpanda SQL read model for %s,\n", typeName, protoFQN)
	fmt.Fprintf(&b, "// read from the external catalog table %s => %s.\n", p.Catalog, p.Table)
	b.WriteString("//\n")
	b.WriteString("// The catalog read is wrapped in a CTE (only the seed is raw); build the\n")
	b.WriteString("// outer query type-safely with the accessors below. Compose with\n")
	fmt.Fprintf(&b, "// postgres.WITH(%s{}.CTE())(postgres.SELECT(...).FROM(...)).\n", typeName)
	fmt.Fprintf(&b, "type %s struct {\n", typeName)
	b.WriteString("\tct rpsql.CatalogTable\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// New%s builds the read model over %s => %s.\n", typeName, p.Catalog, p.Table)
	fmt.Fprintf(&b, "func New%s() %s {\n", typeName, typeName)
	fmt.Fprintf(&b, "\treturn %s{ct: rpsql.NewCatalogTable(%q, %q, %q)}\n", typeName, p.CTEName, p.Catalog, p.Table)
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// CTE returns the catalog CTE; pass it to postgres.WITH(...) and use it as\n")
	b.WriteString("// the FROM target of the outer query.\n")
	fmt.Fprintf(&b, "func (t %s) CTE() postgres.CommonTableExpression { return t.ct.CTE() }\n\n", typeName)

	for _, a := range p.Accessors {
		if a.SQL != "" {
			fmt.Fprintf(&b, "// %s reads %s.\n", a.Method, a.SQL)
		}
		fmt.Fprintf(&b, "func (t %s) %s() %s { return %s }\n\n", typeName, a.Method, a.Return, a.Body)
	}

	if len(p.SkippedRepeated) > 0 {
		b.WriteString("// Omitted fields (repeated / map): rpsql cannot yet read array or\n")
		b.WriteString("// composite-array columns, so these have no accessor:\n")
		for _, s := range p.SkippedRepeated {
			fmt.Fprintf(&b, "//   - %s\n", s)
		}
	}

	return b.String()
}
