package main

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/compiler/protogen"
)

// TestFilterableJetFields pins the filtering-surface decision table
// directly, without going through renderAliases. Keeps the gate rule
// visible next to the kinds whose filterability status it pins.
func TestFilterableJetFields(t *testing.T) {
	t.Parallel()
	p := &ResourcePlan{
		Columns: []ColumnPlan{
			// Synthesized never filterable, even if the kind would be.
			{DBName: "tenant_id", JetFieldName: "TenantID", Kind: KindSynthesized, JetGoType: "string", Synthesized: true},

			// Scalars pass — except the []byte variant (no cursor codec).
			{DBName: "name", JetFieldName: "Name", Kind: KindScalar, JetGoType: "string"},
			{DBName: "enabled", JetFieldName: "Enabled", Kind: KindScalar, JetGoType: "bool"},
			{DBName: "priority", JetFieldName: "Priority", Kind: KindScalar, JetGoType: "int32"},
			{DBName: "count", JetFieldName: "Count", Kind: KindScalar, JetGoType: "int64"},
			{DBName: "blob", JetFieldName: "Blob", Kind: KindScalar, JetGoType: "[]byte"},

			// Timestamps and enums pass.
			{DBName: "created_at", JetFieldName: "CreatedAt", Kind: KindTimestamp, JetGoType: "time.Time"},
			{DBName: "type", JetFieldName: "Type", Kind: KindEnumAsText, JetGoType: "string"},

			// Durations ARE filterable — stored as BIGINT ns, bind through
			// integerOp, accept bare int or duration("5m").
			{DBName: "ttl", JetFieldName: "Ttl", Kind: KindDuration, JetGoType: "int64"},

			// Repeated-text kinds participate via the array path —
			// `zones = "us-west-1"` compiles to `'us-west-1' = ANY(zones)`.
			{DBName: "scopes", JetFieldName: "Scopes", Kind: KindRepeatedText, JetGoType: "pq.StringArray"},
			{DBName: "roles", JetFieldName: "Roles", Kind: KindRepeatedEnum, JetGoType: "pq.StringArray"},

			// Kinds the filter grammar can't express are excluded.
			{DBName: "metadata", JetFieldName: "Metadata", Kind: KindJSONBProto, JetGoType: "string"},
			{DBName: "tags", JetFieldName: "Tags", Kind: KindJSONBStrMap, JetGoType: "string"},
			{DBName: "events", JetFieldName: "Events", Kind: KindJSONBProtoList, JetGoType: "string"},
		},
	}
	got := filterableJetFields(p)
	wantKeys := []string{"name", "enabled", "priority", "count", "created_at", "type", "ttl", "scopes", "roles"}

	haveKeys := make([]string, 0, len(got))
	for _, f := range got {
		haveKeys = append(haveKeys, f.Key)
	}
	assert.Equal(t, wantKeys, haveKeys, "filterable surface mismatch")

	// Declaration order preserved — the emitter relies on this to keep
	// generated aliases.go byte-deterministic across runs.
	assert.Equal(t, "Name", got[0].JetField)
	assert.Equal(t, "Roles", got[len(got)-1].JetField)
}

// Fixture builder — a ResourcePlan that exercises the interesting
// shapes of renderAliases without touching protogen internals. The PK
// covers tenant-synthesized and user-provided fields, one column is
// immutable (drops out of UpdateAll), one is a oneof (two jet fields
// on the same column pair), and updated_at must participate. Kind
// and JetGoType are populated so filterableJetFields has real types
// to dispatch on.
func aliasFixture() *ResourcePlan {
	return &ResourcePlan{
		ProtoFile:      "proto/fixture.proto",
		GoPackageName:  "storage",
		GoDir:          "gen/storage",
		FilenamePrefix: "widget",
		SymbolPrefix:   "Widget",
		JetStructName:  "Widgets",
		JetModelImport: "github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/fixture/storage/jet/public/model",
		JetTableImport: "github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/fixture/storage/jet/public/table",
		PrimaryKey:     []string{"tenant_id", "name"},
		Columns: []ColumnPlan{
			{DBName: "tenant_id", JetFieldName: "TenantID", Kind: KindSynthesized, JetGoType: "string", Synthesized: true},
			{DBName: "name", JetFieldName: "Name", Kind: KindScalar, JetGoType: "string"},
			{DBName: "display_name", JetFieldName: "DisplayName", Kind: KindScalar, JetGoType: "string"},
			{DBName: "created_at", JetFieldName: "CreatedAt", Kind: KindTimestamp, JetGoType: "time.Time", Immutable: true},
			{DBName: "updated_at", JetFieldName: "UpdatedAt", Kind: KindTimestamp, JetGoType: "time.Time"},
		},
		OneofColumns: []OneofColumnPlan{
			{
				BaseName:     "provider_config",
				JetKindField: "ProviderConfigKind",
				JetJSONField: "ProviderConfig",
			},
		},
	}
}

// TestRenderAliases_HeaderAndImports pins the generated file preamble.
// The `_ "embed"` blank import is load-bearing: the go:embed directive
// on <Prefix>DDL requires the blank import for protogen-friendly
// output.
func TestRenderAliases_HeaderAndImports(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "example.v1.Widget")

	assert.Contains(t, got, "// Code generated by protoc-gen-go-jet. DO NOT EDIT.")
	assert.Contains(t, got, "// Source: proto/fixture.proto")
	assert.Contains(t, got, "package storage")
	assert.Contains(t, got, `_ "embed" // needed for the go:embed directive on WidgetDDL below.`)
	assert.Contains(t, got, `"github.com/go-jet/jet/v2/postgres"`)
	assert.Contains(t, got, `model "github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/fixture/storage/jet/public/model"`)
	assert.Contains(t, got, `table "github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/fixture/storage/jet/public/table"`)
}

// TestRenderAliases_ResourceType locks in the FQN constant.
func TestRenderAliases_ResourceType(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "example.v1.Widget")
	assert.Contains(t, got, `const WidgetResourceType = "example.v1.Widget"`)
}

// TestRenderAliases_ModelAndTable pins the alias shape — callers rely
// on <Prefix>Model and <Prefix>Table living in the same package with
// fixed names.
func TestRenderAliases_ModelAndTable(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "x.Widget")
	assert.Contains(t, got, "type WidgetModel = model.Widgets")
	assert.Contains(t, got, "var WidgetTable = table.Widgets")
}

// TestRenderAliases_UpdateAllColumns is the anti-regression for the
// silent-update-drop class of bug: <Prefix>UpdateAll must include
// every mutable column of the fixture, in declaration order, followed
// by the oneof pair.
//
// Asserts against the UpdateAll function body specifically (not the
// whole file) because FilterFields below references the same column
// names and substring checks on the whole file would collide.
func TestRenderAliases_UpdateAllColumns(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "x.Widget")
	body := funcBody(t, got, "func WidgetUpdateAll() postgres.UpdateStatement {")

	// Exclusions:
	// - tenant_id / TenantID: synthesized, skipped.
	// - name / Name: PK member, skipped.
	// - created_at / CreatedAt: immutable, skipped.
	assert.NotContains(t, body, "WidgetTable.TenantID,")
	assert.NotContains(t, body, "WidgetTable.Name,")
	assert.NotContains(t, body, "WidgetTable.CreatedAt,")

	// Inclusions, in order.
	want := []string{
		"WidgetTable.DisplayName,",
		"WidgetTable.UpdatedAt,",
		"WidgetTable.ProviderConfigKind,",
		"WidgetTable.ProviderConfig,",
	}
	idx := 0
	for line := range strings.SplitSeq(body, "\n") {
		line = strings.TrimSpace(line)
		if idx < len(want) && line == want[idx] {
			idx++
		}
	}
	assert.Equal(t, len(want), idx, "expected every mutable column in declaration order; matched %d of %d\nBody:\n%s", idx, len(want), body)
}

// TestRenderAliases_UpdateAllExcludesGeneratedColumn pins the new
// skip rule: a column carrying GeneratedExpr is omitted from the
// UPDATE list. PG would reject `UPDATE ... SET total = ...` on a
// GENERATED ALWAYS column anyway; the plugin keeps it out of the SET
// list so callers can safely use UpdateAll() across rows that
// include a generated column without writing a hand-curated subset.
func TestRenderAliases_UpdateAllExcludesGeneratedColumn(t *testing.T) {
	t.Parallel()
	p := aliasFixture()
	p.Columns = append(p.Columns, ColumnPlan{
		DBName:        "total_microcents",
		JetFieldName:  "TotalMicrocents",
		Kind:          KindScalar,
		JetGoType:     "int64",
		GeneratedExpr: "input_microcents + output_microcents",
	})
	got := renderAliases(p, "x.Widget")
	body := funcBody(t, got, "func WidgetUpdateAll() postgres.UpdateStatement {")

	assert.NotContains(t, body, "WidgetTable.TotalMicrocents,",
		"generated column must be excluded from UpdateAll()")
}

// TestMutableJetFields_ExcludesGeneratedColumn pins the same rule at
// the helper level — keeps the predicate documented next to the
// fixture even if the rendered output ever changes.
func TestMutableJetFields_ExcludesGeneratedColumn(t *testing.T) {
	t.Parallel()
	p := &ResourcePlan{
		PrimaryKey: []string{"id"},
		Columns: []ColumnPlan{
			{DBName: "id", JetFieldName: "ID", Kind: KindScalar, JetGoType: "string"},
			{DBName: "label", JetFieldName: "Label", Kind: KindScalar, JetGoType: "string"},
			{
				DBName:        "computed",
				JetFieldName:  "Computed",
				Kind:          KindScalar,
				JetGoType:     "int64",
				GeneratedExpr: "1 + 1",
			},
		},
	}
	got := mutableJetFields(p)
	assert.Equal(t, []string{"Label"}, got, "PK + generated columns must be excluded; only Label remains")
}

// funcBody slices the generated source between the opening `{` of the
// named function and its matching closing `}` at column 0. Brittle if
// the generator ever emits nested `}` at column 0, but the aliases.go
// emitter doesn't.
func funcBody(t *testing.T, source, header string) string {
	t.Helper()
	start := strings.Index(source, header)
	require.Greaterf(t, start, -1, "function header %q not found in source", header)
	rest := source[start:]
	end := strings.Index(rest, "\n}\n")
	require.Greater(t, end, 0)
	return rest[:end]
}

// TestRenderAliases_DDLEmbed pins the go:embed directive that powers
// the DDL string — tests and fixtures use it to apply the schema
// without reaching for the migrations directory.
func TestRenderAliases_DDLEmbed(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "x.Widget")
	assert.Contains(t, got, "//go:embed widget_ddl.sql")
	assert.Contains(t, got, "var WidgetDDL string")
}

// TestRenderAliases_Deterministic ensures two calls with the same
// input produce byte-identical output. Codegen determinism matters for
// the drift-check (`git diff` on generated files must be stable).
func TestRenderAliases_Deterministic(t *testing.T) {
	t.Parallel()
	a := renderAliases(aliasFixture(), "x.Widget")
	b := renderAliases(aliasFixture(), "x.Widget")
	assert.Equal(t, a, b)
}

// TestRenderAliases_EmittedCodeParses runs the emitter output through
// go/parser to catch any syntactic regression — missing braces, stray
// comma, malformed struct literal, etc. Template-style codegen is
// easy to break silently; this turns "did the emitter produce valid
// Go?" into a red test instead of a compile error downstream.
func TestRenderAliases_EmittedCodeParses(t *testing.T) {
	t.Parallel()
	src := renderAliases(aliasFixture(), "x.Widget")
	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "widget_aliases.go", src, parser.ParseComments)
	require.NoError(t, err, "emitted aliases.go must be syntactically valid Go:\n%s", src)
}

// TestRenderAliases_FilterFieldsIncludesCursorCapable pins the
// filterability surface: the generated <Prefix>FilterFields() must
// list every column whose kind has a cursor codec (scalar string/
// bool/int, timestamp, enum-as-text, duration) and must exclude the
// ones the grammar can't express (JSONB, TEXT[], BYTEA, synthesized).
// Excluded kinds would be rejected by the translator at query time
// anyway — hiding them at generation time stops callers from
// writing filters that can only fail.
func TestRenderAliases_FilterFieldsIncludesCursorCapable(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "x.Widget")

	require.Contains(t, got, "func WidgetFilterFields() aipjet.FilterFields {")
	require.Contains(t, got, `"name": WidgetTable.Name,`)
	require.Contains(t, got, `"display_name": WidgetTable.DisplayName,`)
	require.Contains(t, got, `"created_at": WidgetTable.CreatedAt,`)
	require.Contains(t, got, `"updated_at": WidgetTable.UpdatedAt,`)

	// tenant_id is synthesized — must never appear as a filter key,
	// letting a caller filter by tenant_id would bypass the service's
	// implicit scoping.
	assert.NotContains(t, got, `"tenant_id"`)
}

// TestRenderAliases_FilterFieldsExcludesUnbindable covers the kinds
// the filter grammar cannot express — JSONB, BYTEA. They must NOT
// appear in FilterFields (the translator would reject them anyway;
// exposing them at generation time is a UX trap). Durations ARE
// filterable (BIGINT ns via integerOp) and stay in. Repeated-text
// kinds (TEXT[]) also bind now — they route through stringArrayOp
// and compile to `value = ANY(col)`.
func TestRenderAliases_FilterFieldsExcludesUnbindable(t *testing.T) {
	t.Parallel()
	p := aliasFixture()
	p.Columns = append(p.Columns,
		ColumnPlan{DBName: "metadata", JetFieldName: "Metadata", Kind: KindJSONBProto, JetGoType: "string"},
		ColumnPlan{DBName: "scopes", JetFieldName: "Scopes", Kind: KindRepeatedText, JetGoType: "pq.StringArray"},
		ColumnPlan{DBName: "ttl", JetFieldName: "Ttl", Kind: KindDuration, JetGoType: "int64"},
		ColumnPlan{DBName: "payload", JetFieldName: "Payload", Kind: KindScalar, JetGoType: "[]byte"},
	)
	got := renderAliases(p, "x.Widget")

	require.Contains(t, got, "func WidgetFilterFields() aipjet.FilterFields {")
	assert.NotContains(t, got, `"metadata"`)
	assert.NotContains(t, got, `"payload"`)
	// Duration binds through integerOp.
	assert.Contains(t, got, `"ttl": WidgetTable.Ttl,`)
	// Repeated text binds through stringArrayOp.
	assert.Contains(t, got, `"scopes": WidgetTable.Scopes,`)
}

// TestRenderAliases_FilterFieldsIncludesNullableScalar pins that a
// nullable scalar column stays filterable. Nullability renders the
// model field as a pointer (*string), but the jet table column is the
// same ColumnString and binds to an AIP-160 comparison identically —
// excluding it would silently break server-side filters like
// `guardrail = "x"` on a column the moment it goes optional.
func TestRenderAliases_FilterFieldsIncludesNullableScalar(t *testing.T) {
	t.Parallel()
	p := aliasFixture()
	p.Columns = append(p.Columns,
		ColumnPlan{DBName: "guardrail", JetFieldName: "Guardrail", Kind: KindScalar, JetGoType: "*string"},
		ColumnPlan{DBName: "retries", JetFieldName: "Retries", Kind: KindScalar, JetGoType: "*int64"},
	)
	got := renderAliases(p, "x.Widget")

	assert.Contains(t, got, `"guardrail": WidgetTable.Guardrail,`)
	assert.Contains(t, got, `"retries": WidgetTable.Retries,`)
}

// TestRenderAliases_FilterFieldsImport ensures the generated file
// carries the aipjet import — callers copy-pasting `gen.XFilterFields()`
// into their repo must get a file that compiles on its own.
func TestRenderAliases_FilterFieldsImport(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "x.Widget")
	assert.Contains(t, got, `aipjet "github.com/redpanda-data/protoc-gen-go-jet/pkg/aip/jet"`)
}

// TestRenderAliases_NoOneofOmitsOneofPair covers the shape with no
// oneof — the UpdateAll column list should contain only non-PK,
// non-synthesized, non-immutable jet fields.
func TestRenderAliases_NoOneofOmitsOneofPair(t *testing.T) {
	t.Parallel()
	p := aliasFixture()
	p.OneofColumns = nil

	got := renderAliases(p, "x.Widget")
	body := funcBody(t, got, "func WidgetUpdateAll() postgres.UpdateStatement {")
	assert.Contains(t, body, "WidgetTable.DisplayName,")
	assert.Contains(t, body, "WidgetTable.UpdatedAt,")
	assert.NotContains(t, body, "ProviderConfigKind")
	assert.NotContains(t, body, "ProviderConfig,")
}

// TestRenderAliases_OptionalOneofInUpdateAll pins that an Optional
// oneof still contributes both kind + json fields to UpdateAll. The
// optional bit only affects the DDL CHECK (admits blank discriminator);
// mutating the pair has to clear both columns when the caller flips
// back to "no variant", so UpdateAll MUST write them. A codegen that
// special-cased Optional by dropping the pair would silently skip the
// column on updates, leaving the previous variant's discriminator +
// JSON in place.
func TestRenderAliases_OptionalOneofInUpdateAll(t *testing.T) {
	t.Parallel()
	p := aliasFixture()
	p.OneofColumns = []OneofColumnPlan{
		{
			BaseName:     "provider_config",
			JetKindField: "ProviderConfigKind",
			JetJSONField: "ProviderConfig",
			Optional:     true,
		},
	}
	got := renderAliases(p, "x.Widget")
	body := funcBody(t, got, "func WidgetUpdateAll() postgres.UpdateStatement {")
	assert.Contains(t, body, "WidgetTable.ProviderConfigKind,")
	assert.Contains(t, body, "WidgetTable.ProviderConfig,")
}

// TestRenderAliases_OneofPairNotFilterable pins that the oneof pair
// stays out of FilterFields. Both columns are persisted — the kind
// column is TEXT (structurally like a scalar the translator could
// bind) and the json column is JSONB (rejected by the translator).
// Exposing either through FilterFields would tempt callers to filter
// by raw variant name instead of using a structured API, bypassing
// the protobuf abstraction and coupling their queries to the storage
// layer's discriminator strings.
func TestRenderAliases_OneofPairNotFilterable(t *testing.T) {
	t.Parallel()
	got := renderAliases(aliasFixture(), "x.Widget")

	// The fixture's oneof pair is ProviderConfigKind + ProviderConfig.
	// Neither may show up as a filter key.
	assert.NotContains(t, got, `"provider_config_kind"`)
	assert.NotContains(t, got, `"provider_config":`)
	assert.NotContains(t, got, "WidgetTable.ProviderConfigKind,\n\t\t\"")
	// Belt-and-braces: the FilterFields body specifically must not
	// reference the oneof jet fields.
	fields := funcBody(t, got, "func WidgetFilterFields() aipjet.FilterFields {")
	assert.NotContains(t, fields, "ProviderConfigKind")
	assert.NotContains(t, fields, "WidgetTable.ProviderConfig,")
}

// TestJsonbFilterPaths — direct unit coverage for the helper that
// assembles the auto-registered FilterFields entries for both
// `Column.jsonb_indexed_paths` and `OneofColumn.jsonb_indexed_paths`.
// Integration tests via ClusterLike exercise both branches end-to-
// end, but the helper itself deserves focused tests so a regression
// in shape / ordering is caught without a testcontainer.
func TestJsonbFilterPaths(t *testing.T) {
	t.Parallel()

	t.Run("column paths only", func(t *testing.T) {
		t.Parallel()
		p := &ResourcePlan{
			Columns: []ColumnPlan{
				{DBName: "config", Kind: KindJSONBProto, JSONBIndexedPaths: []string{"api_key", "nested.timeout"}},
			},
		}
		got := jsonbFilterPaths(p)
		assert.Equal(t, []jsonbFilterPath{
			{Key: "config.api_key", Expr: "config->>'api_key'"},
			{Key: "config.nested.timeout", Expr: "config->'nested'->>'timeout'"},
		}, got)
	})

	t.Run("oneof paths only", func(t *testing.T) {
		t.Parallel()
		p := &ResourcePlan{
			OneofColumns: []OneofColumnPlan{
				{
					BaseName:          "cloud",
					KindColumn:        "cloud_kind",
					JSONColumn:        "cloud",
					JSONBIndexedPaths: []string{"accountId"},
				},
			},
		}
		got := jsonbFilterPaths(p)
		assert.Equal(t, []jsonbFilterPath{
			{Key: "cloud.accountId", Expr: "cloud->>'accountId'"},
		}, got)
	})

	t.Run("both column + oneof paths — columns first, oneofs second", func(t *testing.T) {
		t.Parallel()
		// Emission order matters: column entries precede oneof
		// entries in the generated FilterFields map literal. Order
		// within each group follows declaration order in the plan.
		p := &ResourcePlan{
			Columns: []ColumnPlan{
				{DBName: "spec", Kind: KindJSONBProto, JSONBIndexedPaths: []string{"version"}},
				{DBName: "attrs", Kind: KindJSONBStrMap, JSONBIndexedPaths: []string{"env"}},
			},
			OneofColumns: []OneofColumnPlan{
				{BaseName: "cloud", JSONColumn: "cloud", JSONBIndexedPaths: []string{"accountId"}},
			},
		}
		got := jsonbFilterPaths(p)
		require.Len(t, got, 3)
		assert.Equal(t, "spec.version", got[0].Key)
		assert.Equal(t, "attrs.env", got[1].Key)
		assert.Equal(t, "cloud.accountId", got[2].Key, "oneof path must follow column paths")
	})

	t.Run("no paths — nil result", func(t *testing.T) {
		t.Parallel()
		p := &ResourcePlan{
			Columns: []ColumnPlan{
				{DBName: "name", Kind: KindScalar, JSONBIndexedPaths: nil},
			},
		}
		got := jsonbFilterPaths(p)
		assert.Nil(t, got)
	})

	t.Run("column with empty paths list is equivalent to no paths", func(t *testing.T) {
		t.Parallel()
		p := &ResourcePlan{
			Columns: []ColumnPlan{
				{DBName: "config", Kind: KindJSONBProto, JSONBIndexedPaths: []string{}},
			},
		}
		got := jsonbFilterPaths(p)
		assert.Nil(t, got)
	})
}

// TestRenderAliases_StampHelpers asserts that when a ResourcePlan contains
// created_by and updated_by columns, renderAliases emits StampCreate and
// StampUpdate helper functions, and that the generated code is valid Go.
func TestRenderAliases_StampHelpers(t *testing.T) {
	t.Parallel()
	p := &ResourcePlan{
		ProtoFile:      "proto/example/v1/llmprovider.proto",
		GoPackageName:  "storage",
		GoDir:          "gen/storage",
		FilenamePrefix: "llmprovider",
		SymbolPrefix:   "LLMProvider",
		JetStructName:  "LlmProviders",
		JetModelImport: "github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/example/v1/storage/jet/public/model",
		JetTableImport: "github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/example/v1/storage/jet/public/table",
		PrimaryKey:     []string{"tenant_id", "id"},
		ProtoGoIdent: protogen.GoIdent{
			GoImportPath: "github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/example/v1",
			GoName:       "LLMProvider",
		},
		Columns: []ColumnPlan{
			{DBName: "tenant_id", JetFieldName: "TenantID", Kind: KindSynthesized, JetGoType: "string", Synthesized: true},
			{DBName: "id", JetFieldName: "ID", Kind: KindScalar, JetGoType: "string"},
			{DBName: "display_name", JetFieldName: "DisplayName", Kind: KindScalar, JetGoType: "string"},
			{DBName: "created_at", JetFieldName: "CreatedAt", Kind: KindTimestamp, JetGoType: "time.Time", Immutable: true},
			{DBName: "updated_at", JetFieldName: "UpdatedAt", Kind: KindTimestamp, JetGoType: "time.Time"},
			{DBName: "created_by", JetFieldName: "CreatedBy", Kind: KindScalar, JetGoType: "string", ProtoFieldName: "created_by", Immutable: true},
			{DBName: "updated_by", JetFieldName: "UpdatedBy", Kind: KindScalar, JetGoType: "string", ProtoFieldName: "updated_by"},
		},
	}

	got := renderAliases(p, "example.v1.LLMProvider")

	assert.Contains(t, got, "func LLMProviderStampCreate(", "StampCreate helper must be emitted when created_by column is present")
	assert.Contains(t, got, "func LLMProviderStampUpdate(", "StampUpdate helper must be emitted when updated_by column is present")
	assert.Contains(t, got, `"github.com/redpanda-data/protoc-gen-go-jet/proto/gen/go/example/v1"`, "proto import path must appear in generated imports")

	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "llmprovider_aliases.go", got, parser.ParseComments)
	require.NoError(t, err, "emitted aliases.go with stamp helpers must be syntactically valid Go:\n%s", got)
}

// TestRenderAliases_NoStampHelpers_WhenFieldsAbsent asserts that when a
// ResourcePlan has no created_by or updated_by columns, renderAliases does
// NOT emit StampCreate or StampUpdate.
func TestRenderAliases_NoStampHelpers_WhenFieldsAbsent(t *testing.T) {
	t.Parallel()
	// aliasFixture has no created_by / updated_by columns.
	got := renderAliases(aliasFixture(), "x.Widget")

	assert.NotContains(t, got, "StampCreate", "StampCreate must not be emitted when created_by column is absent")
	assert.NotContains(t, got, "StampUpdate", "StampUpdate must not be emitted when updated_by column is absent")
}
