package main

import (
	"errors"
	"fmt"
	"path/filepath"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	aipPkg    = "github.com/redpanda-data/protoc-gen-go-jet/pkg/aip"
	aipjetPkg = "github.com/redpanda-data/protoc-gen-go-jet/pkg/aip/jet"
)

// emitSchema writes schema_gen.go — the aipjet.Schema declaration used by
// the repository's List implementation.
func emitSchema(gen *protogen.Plugin, p *ResourcePlan) error {
	// Reject orderable fields with no well-defined cursor codec early
	// so we fail loudly rather than emitting a broken schema.
	for _, c := range p.Columns {
		if !c.Orderable || c.Synthesized {
			continue
		}
		if err := validateOrderable(c); err != nil {
			return fmt.Errorf("%s: field %s: %w", columnSourceLoc(c), c.DBName, err)
		}
	}

	relPath := filepath.Join(p.GoDir, p.FilenamePrefix+"_schema.go")
	g := gen.NewGeneratedFile(relPath, protogen.GoImportPath(p.GoImportPath))

	g.P("// Code generated by protoc-gen-go-jet. DO NOT EDIT.")
	g.P("// Source: ", p.ProtoFile)
	g.P()
	g.P("package ", p.GoPackageName)
	g.P()

	aipjetIdent := protogen.GoIdent{GoImportPath: aipjetPkg, GoName: "NewSchema"}
	tableIdent := protogen.GoIdent{GoImportPath: protogen.GoImportPath(p.JetTableImport), GoName: p.JetStructName}
	modelIdent := protogen.GoIdent{GoImportPath: protogen.GoImportPath(p.JetModelImport), GoName: p.JetStructName}

	// resource type string: "<proto package>.<message>"
	protoFQN := fmt.Sprintf("%s.%s", p.Message.Desc.ParentFile().Package(), p.Message.Desc.Name())

	g.P("// ", p.SymbolPrefix, "ListSchema describes pagination / ordering for ", p.ProtoGoName, " lists.")
	g.P("var ", p.SymbolPrefix, "ListSchema = ", aipjetIdent, "[", modelIdent, "](")
	g.P("    \"", protoFQN, "\",")
	g.P("    ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: aipjetPkg, GoName: "Fields"}), "[", modelIdent, "]{")

	for _, c := range p.Columns {
		if !c.Orderable || c.Synthesized {
			continue
		}
		codec := codecForColumn(c, g)
		g.P("        \"", c.DBName, "\": {")
		g.P("            Column:   ", tableIdent, ".", c.JetFieldName, ",")
		g.P("            Codec:    ", codec, ",")
		g.P("            GetValue: func(m *", modelIdent, ") any { return m.", c.JetFieldName, " },")
		g.P("        },")
	}
	g.P("    },")

	// Default order
	withDefaultOrder := protogen.GoIdent{GoImportPath: aipjetPkg, GoName: "WithDefaultOrder"}
	withTieBreaker := protogen.GoIdent{GoImportPath: aipjetPkg, GoName: "WithTieBreaker"}
	aipAsc := protogen.GoIdent{GoImportPath: aipPkg, GoName: "Asc"}
	aipDesc := protogen.GoIdent{GoImportPath: aipPkg, GoName: "Desc"}

	for _, part := range p.DefaultOrder {
		dir := aipAsc
		if part.Desc {
			dir = aipDesc
		}
		g.P("    ", withDefaultOrder, "(\"", part.FieldPath, "\", ", dir, "),")
	}
	for _, part := range p.TieBreaker {
		dir := aipAsc
		if part.Desc {
			dir = aipDesc
		}
		g.P("    ", withTieBreaker, "(\"", part.FieldPath, "\", ", dir, "),")
	}

	g.P(")")
	return nil
}

// validateOrderable returns an error for orderable fields whose kind has
// no well-defined cursor codec. Pagination compares cursor values via the
// codec; an unsupported kind would produce semantically wrong results
// (e.g. sorting on raw JSONB bytes). Better to refuse at generation time
// than to ship subtly broken pagination.
//
// Bool is intentionally excluded: go-jet's BoolExpression has no GT/LT,
// so the lexicographic cursor fallback can't emit a "skip past this
// boolean value" predicate. Two-valued ordering also provides near-
// zero pagination benefit — the tie-breaker does all the actual work.
// If you need bool-first ordering, encode it as a derived int column.
func validateOrderable(c ColumnPlan) error {
	// Nullable columns break keyset pagination without a NULL-aware
	// comparator. The jet model renders nullable scalars as pointers
	// (*string, *int64, ...) which the cursor codec's Encode
	// signature doesn't accept, and the comparator has no branch for
	// the NULL partition of the sort order (NULLS FIRST/LAST).
	// Refusing at generation time beats a runtime type-assert panic
	// or silently-wrong pagination past the first NULL.
	if c.Nullable {
		return errors.New("orderable nullable columns aren't supported — the keyset comparator isn't NULL-aware and the cursor codec doesn't accept pointer values; COALESCE in a generated expression column or drop `orderable: true` until the NULL-aware keyset lands")
	}
	switch c.Kind {
	case KindTimestamp, KindDuration, KindEnumAsText:
		return nil
	case KindScalar:
		switch c.JetGoType {
		case "string", "int32", "int64", "float32", "float64":
			return nil
		case "bool":
			return errors.New("orderable bool columns aren't supported — jet's BoolExpression lacks GT/LT and two-valued ordering doesn't add pagination signal beyond the tie-breaker")
		}
		return fmt.Errorf("orderable scalar with JetGoType %q has no cursor codec", c.JetGoType)
	}
	return fmt.Errorf("orderable fields must be scalar / timestamp / duration / enum — got %s", c.Kind)
}

// codecForColumn returns a qualified identifier for the aip.CursorCodec
// that pages this column. Caller is expected to have validated the field
// via validateOrderable first — so bool never reaches here even though
// aip.BoolCodec exists in the codec family.
func codecForColumn(c ColumnPlan, g *protogen.GeneratedFile) string {
	return g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: aipPkg, GoName: codecNameForColumn(c)}) + "{}"
}

// codecNameForColumn returns the unqualified aip codec type name for a
// column's kind + Go type. Split from codecForColumn so the decision
// logic can be unit-tested without a GeneratedFile fixture — any
// future codec addition must round-trip through this function.
func codecNameForColumn(c ColumnPlan) string {
	switch c.Kind {
	case KindTimestamp:
		return "TimestampCodec"
	case KindDuration:
		return "Int64Codec"
	case KindScalar:
		if c.JetGoType == "int32" || c.JetGoType == "int64" {
			return "Int64Codec"
		}
		if c.JetGoType == "float32" || c.JetGoType == "float64" {
			return "Float64Codec"
		}
	}
	// Default (string-valued scalars, enum-as-text): string codec.
	return "StringCodec"
}
